function project_root = setup_paths()
%SETUP_PATHS Add project source folders to the MATLAB path.

project_root = fileparts(mfilename('fullpath'));

folders = { ...
    fullfile(project_root, 'config'), ...
    fullfile(project_root, 'representation'), ...
    fullfile(project_root, 'crypto'), ...
    fullfile(project_root, 'evaluation'), ...
    fullfile(project_root, 'tests') ...
};

for i = 1:numel(folders)
    addpath(folders{i});
end
end
